### ISSUE TITLE
[BUG] Doesn't respect the disable_mpris config

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-media#18]
Running on Mac OS:

mycroft.conf
```jsonc
{
  "media": {
    "preferred_audio_services": ["vlc"],
    "preferred_web_services": ["browser"],
    "preferred_video_services": ["vlc"],
    "disable_mpris": true,
    "manage_external_players": true
  }
}
```

But when loading ovos-media:

```zsh
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/dbus/machine-id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/ovos-mac-4gtofNfg-py3.11/lib/python3.11/site-packages/ovos_media/mpris.py", line 639, in run
    self.loop.run_until_complete(self.event_loop())
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/ovos-mac-4gtofNfg-py3.11/lib/python3.11/site-packages/ovos_media/mpris.py", line 581, in event_loop
    self.dbus = await DbusMessageBus(
                      ^^^^^^^^^^^^^^^
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/ovos-mac-4gtofNfg-py3.11/lib/python3.11/site-packages/dbus_next/aio/message_bus.py", line 122, in __init__
    super().__init__(bus_address, bus_type, ProxyObject)
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/ovos-mac-4gtofNfg-py3.11/lib/python3.11/site-packages/dbus_next/message_bus.py", line 72, in __init__
    get_bus_address(bus_type))
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/ovos-mac-4gtofNfg-py3.11/lib/python3.11/site-packages/dbus_next/_private/address.py", line 98, in get_bus_address
    return get_session_bus_address()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Mike/Library/Caches/pypoetry/virtualenvs/ovos-mac-4gtofNfg-py3.11/lib/python3.11/site-packages/dbus_next/_private/address.py", line 72, in get_session_bus_address
    with open('/var/lib/dbus/machine-id') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/dbus/machine-id'
2024-03-27 23:00:57.883 - media - ovos_utils:wait_for_exit_signal:148 - DEBUG - Exiting on KeyboardInterrupt
2024-03-27 23:00:57.890 - media - ovos_media.service:on_stopping:29 - INFO - Audio service is shutting down...
2024-03-27 23:00:57.892 - media - ovos_media.player:stop:905 - DEBUG - Stopping playback
```

**Comment by JarbasAl** [comment]
fixed by https://github.com/OpenVoiceOS/ovos-media/pull/19
