### ISSUE TITLE
When music is playing, gui complains about missing file

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-media#22]
```
 14:44:48.103 - gui - ovos_gui.namespace:_add_pages:324 - DEBUG - Updating qt5 client
~~~~:327 - ERROR - Error updating qt5 client: Unable to resolve resource file for resource Home.qml for framework qt5
Traceback (most recent call last):
  File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_gui/namespace.py", line 325, in _add_pages
    client.send_gui_pages(new_pages, self.skill_id, position)
  File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_gui/bus.py", line 272, in send_gui_pages
    "data": [{"url": page.get_uri(framework, server_url)}
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_gui/bus.py", line 272, in <listcomp>
    "data": [{"url": page.get_uri(framework, server_url)}
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_gui/page.py", line 86, in get_uri
    raise FileNotFoundError(f"Unable to resolve resource file for "
FileNotFoundError: Unable to resolve resource file for resource Home.qml for framework qt5
```

**Comment by goldyfruit** [comment]
```
 15:36:07.807 - gui - ovos_gui.namespace:_add_pages:324 - DEBUG - Updating qt5 client
~~~~OR - Error updating qt5 client: Unable to resolve resource file for resource SearchingMedia.qml for framework qt5
Traceback (most recent call last):
  File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_gui/namespace.py", line 325, in _add_pages
    client.send_gui_pages(new_pages, self.skill_id, position)
  File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_gui/bus.py", line 272, in send_gui_pages
    "data": [{"url": page.get_uri(framework, server_url)}
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_gui/bus.py", line 272, in <listcomp>
    "data": [{"url": page.get_uri(framework, server_url)}
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/goldyfruit/.venvs/ovos/lib/python3.11/site-packages/ovos_gui/page.py", line 86, in get_uri
    raise FileNotFoundError(f"Unable to resolve resource file for "
FileNotFoundError: Unable to resolve resource file for resource SearchingMedia.qml for framework qt5
```
